Lab11DeckOfCardsApi/Models/CardDeckApi.cs
namespace Lab11DeckOfCardsApi.Models
{
    public class CardDeckApi
    {
            public bool success { get; set; }
            public string deck_id { get; set; }
            public CardDrawApi[] cards { get; set; }
            public int remaining { get; set; }

            public bool shuffled { get; set; } = true;

    }
}

Lab11DeckOfCardsApi/Models/CardDrawApi.cs
namespace Lab11DeckOfCardsApi.Models
{
    public class CardDrawApi
    {
        public string code { get; set; }
        public string image { get; set; }
        //public CardPhotoApi[] images { get; set; }
        public string value { get; set; }
        public string suit { get; set; }
    }
}

Lab11DeckOfCardsApi/Models/CardPhotoApi.cs
namespace Lab11DeckOfCardsApi.Models
{
    public class CardPhotoApi
    {
        public string png { get; set; }
    }
}

Lab11DeckOfCardsApi/Models/ErrorViewModel.cs
namespace Lab11DeckOfCardsApi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab11DeckOfCardsApi/Controllers/CardDeckController.cs
using Microsoft.AspNetCore.Mvc;
using Flurl.Http;
using Lab11DeckOfCardsApi.Models;

namespace Lab11DeckOfCardsApi.Controllers
{
    public class CardDeckController : Controller
    {
        public IActionResult Index()
        {
            string apiUri = "https://deckofcardsapi.com/api/deck/new/shuffle";
            var apiTask = apiUri.GetJsonAsync<CardDeckApi>();
            apiTask.Wait();
            CardDeckApi cardDeck = apiTask.Result;

            return View(cardDeck);
        }

        public IActionResult CardDetails(CardDeckApi cardDeck, string id)
        {
            string apiUri = $"https://deckofcardsapi.com/api/deck/{id}/draw/?count=5";
            var apiTask = apiUri.GetJsonAsync<CardDeckApi>();
            apiTask.Wait();
            CardDeckApi cardDraw = apiTask.Result;

            return View(cardDraw);
        }
    }
}

Lab11DeckOfCardsApi/Controllers/HomeController.cs
using Lab11DeckOfCardsApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab11DeckOfCardsApi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab11DeckOfCardsApi/Views/CardDeck/CardDetails.cshtml
@model Lab11DeckOfCardsApi.Models.CardDeckApi

@{
    ViewData["Title"] = "Draw 5 Cards";
}

<h1>You Drew 5 Cards:</h1>

<div>
    <hr />
    <dl class="row">
        @foreach (var item in Model.cards)
        {
            <dd class="col=sm-2">
                <span>@item.value of @item.suit</span>
            </dd>
            <dd class="col=sm-2">
                <img src="@item.image">
            </dd>
        }
    </dl>
</div>

Lab11DeckOfCardsApi/Views/CardDeck/Index.cshtml
@model Lab11DeckOfCardsApi.Models.CardDeckApi

@{
    ViewData["Title"] = "New Deck";
}

<form asp-action="CardDetails">
<div>
    <h4>You Have Created A New Deck</h4>
    @*@Html.HiddenFor(m => m.deck_id)*@
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.deck_id)
        </dt>
        <dd class = "col-sm-10" name="deck_id">
            @Html.DisplayFor(model => model.deck_id)
        </dd>
    </dl>
</div>
    <div>
        @Html.ActionLink("Draw", "CardDetails", new { id = Model.deck_id })
        @*<button type="submit">Draw 5 Cards!</button>*@
    </div>
</form>

Lab11DeckOfCardsApi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab11DeckOfCardsApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab 11 - Deck of Cards</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab11DeckOfCardsApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab11DeckOfCardsApi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CardDeck" asp-action="Index">Deck of Cards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lab11DeckOfCardsApi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>